### ISSUE TITLE
Top face of water/lavafalls mistakenly not rendered

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#171]
Waterfalls and lavafalls will occasionally not render the top face. It seems to happen more frequently when the face is at a steeper angle, as seen in the screenshot.

![2020-07-24_19 19 08](https://user-images.githubusercontent.com/57158823/88444497-fc743a80-cde2-11ea-9c59-5a5dc22b3e6d.png)

Notice the taller falls in the middle and left showing the issue, while the smaller fall on the right does not.

**Comment by Erazer750** [comment]
Thats allready a known bug and will be fixed in Sodium 0.2.0.
Its the fancy translucency bug you're describing :)

**Comment by ghost** [comment]
Nice to know. Thanks and sorry for the duplicate issue.

**Comment by LucilleTea** [comment]
To clarify: the issue pictured here is not the lack of vertex sorting that Erazer750 is talking about, which is planned to be fixed in Sodium 0.2 and tracked in #38 
Instead the issue pictured is incorrect culling of the water's faces based on the angle the chunk is viewed at.
This problem has already been fixed by 5840ca2f42b6f2e29c4ae906fa4c95d4a4d86e38

**Comment by amnotbananaama** [comment]
Re-opening until merged into stable

**Comment by jellysquid3** [comment]
Fixed with 772893d9.

**Comment by LucilleTea** [comment]
This issue still occurs in some situations even after commit 772893d9ce2aa166951ebbaae8f33cc64d5d1c74.

![Sodium_View](https://user-images.githubusercontent.com/64509677/98095030-f90c4700-1ed9-11eb-8188-73276269700d.png)

Seed:
`-6705514674227345575`

Location:
`/tp @p -409 67 110 120 -26.6`

Reported by BinaryBreakpoint on the Discord, I've confirmed it.

**Comment by ghost** [comment]
"BinaryBreakpoint" is using windows and in minecraft they use a FOV of 30.

**Comment by madonuko** [comment]
https://user-images.githubusercontent.com/48051237/103494649-c13a6500-4e72-11eb-9a33-939c0b79d414.mp4

I was planning to create a new issue but I found this issue. The title confuses me a lot.  
It wasn't only the top, **but also the side ones**. From my understanding **when one of the sides of the water shares the same pixels as the dirt behind**, sodium decides not to render it.
