### ISSUE TITLE
Incorrect glowing effect color in minecraft 1.21

### ISSUE THREAD

**Issue by wdfaESfaef** [jellysquid3/Sodium#2547]
### Bug Description

I created a team and give myself a glowing effect, then used `/team modify team color red` to modify the team color, but the glow color seems to be incorrect.
![1](https://github.com/CaffeineMC/sodium-fabric/assets/63187438/55d59421-85fc-471d-b4ee-3aa91bdda12d)
![2](https://github.com/CaffeineMC/sodium-fabric/assets/63187438/6ed930fc-e4c5-444d-bff2-8d4a425a5b03)
I tried to start the game without using sodium, and the color was correct

### Reproduction Steps

1. Create a team and join
2. Give yourself a glowing effect
3. Modify team color
4. The glow color does not match the team color

### Log File

[latest.log](https://github.com/user-attachments/files/15855801/latest.log)

### Crash Report

[crash-2024-06-16_08.47.46-client.txt](https://github.com/user-attachments/files/15855802/crash-2024-06-16_08.47.46-client.txt)

**Comment by IMS212** [comment]
Fixed in 0.5.11, releasing soon.

**Comment by IMS212** [comment]
Fixed in https://github.com/CaffeineMC/sodium-fabric/commit/19a25aace8929a3c6bc2221fb1117bf8abbabe44.

**Comment by douira** [comment]
There's [a report](https://discord.com/channels/602796788608401408/1260082015479271535/1262199283302797425) that this is still broken on neoforge.
