### ISSUE TITLE
Game crashes when a resource pack has an empty clouds texture

### ISSUE THREAD

**Issue by Deadman621** [jellysquid3/Sodium#2552]
### Bug Description

When trying to join servers with Sodium 0.5.9 for 1.21, it gives Network Protocol Error and doesn't connect. Sometimes it crashes too without giving any errors.  

### Reproduction Steps

Try connecting to a server with sodium mod enabled. 

### Log File

[Log.txt](https://github.com/user-attachments/files/15874325/Log.txt)

### Crash Report

[Crash Report.txt](https://github.com/user-attachments/files/15874327/Crash.Report.txt)

**Comment by Felix14-v2** [comment]
Are you able to reproduce the crash without Fabric API?

**Comment by Deadman621** [comment]
> Are you able to reproduce the crash without Fabric API?

yes

**Comment by jellysquid3** [comment]
This is caused by the clouds texture in the resource pack being empty. It should be fixed with https://github.com/CaffeineMC/sodium-fabric/commit/0b06ed4083641c7855a5b2a4a5525ac162561ae6, but a release still needs to be made.

**Comment by DanDragonWolf** [comment]
> This is caused by the clouds texture in the resource pack being empty. It should be fixed with [0b06ed4](https://github.com/CaffeineMC/sodium-fabric/commit/0b06ed4083641c7855a5b2a4a5525ac162561ae6), but a release still needs to be made.

Would like to point out real quick that this is also an issue in 1.20.6, possibly other versions too

**Comment by yepidoodles** [comment]
[crash-2024-08-04_14.31.37-client.txt](https://github.com/user-attachments/files/16488665/crash-2024-08-04_14.31.37-client.txt)

My friend is still having this issue in Sodium version 0.5.11 in MC 1.21
