### ISSUE TITLE
White dots on the borders of blocks with a dark texture.

### ISSUE THREAD

**Issue by Vitaki1** [jellysquid3/Sodium#2625]
### Bug Description

There are white dots on the borders of the blocks with a dark texture.
![2024-07-28_03 06 06](https://github.com/user-attachments/assets/09bc0147-0c1e-4769-bcda-3b50dfcd628a)
![2024-07-28_03 06 16](https://github.com/user-attachments/assets/abfd91c9-25a9-4eb8-9261-6906f93a4ae5)
![2024-07-28_03 07 02](https://github.com/user-attachments/assets/74d1cad4-444c-4a29-8b75-13d07270a5b1)
![image](https://github.com/user-attachments/assets/3e6747e4-44af-45c9-a9cc-def08719d38d)
I was checking how it would be WITHOUT Sodium.There were no white dots.

### Reproduction Steps

Make a plane out of blocks with a dark texture and walk along it

### Log File

[latest.log](https://github.com/user-attachments/files/16401800/latest.log)

### Crash Report

[crash-2024-07-28_03.13.37-client.txt](https://github.com/user-attachments/files/16401801/crash-2024-07-28_03.13.37-client.txt)

**Comment by djmrFunnyMan** [comment]
I can reproduce this
![2024-08-08_16 24 33](https://github.com/user-attachments/assets/9095fa44-c006-4c35-9843-b2c7f9283710)
![2024-08-08_16 24 37](https://github.com/user-attachments/assets/dbcf37f6-ac9a-4d9c-a8ab-bb5d48edd9cb)

**Comment by djmrFunnyMan** [comment]
It's most visible when slowly walking sideways. (unless this is another issue)
(Compression really screwed the video up but you can see it anyways)

https://github.com/user-attachments/assets/3899dcd8-7ee7-4228-8951-8591f82e685c

Also it's _not_ just dark textures. I was able to see it on cyan concrete which definitely isn't dark.

**Comment by djmrFunnyMan** [comment]
I did some further testing. The issue is related to the atlas size. 
My eazy reproduction steps for 1.21 are
- load [faithful](https://www.curseforge.com/minecraft/texture-packs/classic-faithful-32x-jappa/files/5603047)
- unload faithful
- the issue now happens

But I discovered one more thing. This issue is already fixed in the 0.6.0 alphas.

**Comment by douira** [comment]
This is fixed on dev and on 0.6. There was a commit fixing it a few weeks ago

**Comment by wirl** [comment]
I am still getting this on 1.21.1 with Sodium as only mod, when it's not used the dots disappear. I am using the latest available version from Modrinth. I am on macOS if that makes things different. I know macOS has less than a stellar OpenGL implementation. I can also reproduce this on Linux but don't have windows installed to test there as well. 

```
[13:56:00] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
[13:56:00] [main/INFO]: Loading 11 mods:
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.1
	- sodium 0.6.0-beta.2+mc1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   \-- fabric-resource-loader-v0 1.3.0+5659912919
```

No other mods or texture packs are used, other than Sodium my test instance is vanilla.

With:
![Screenshot 2024-09-25 at 13 48 43](https://github.com/user-attachments/assets/3b81ee9d-e848-4584-b51e-4737d680d09e)

Without:
![Screenshot 2024-09-25 at 13 50 09](https://github.com/user-attachments/assets/6ef082d5-356e-437d-b99b-645ac63de986)

I will clone the repo and build from source and see if it changes anything compared to Sodium from Modrinth.

**Comment by wirl** [comment]
Compiled the dev branch from source and get the same issue, dots look more colourful but that could be my imagination 😅

```
[14:30:18] [main/INFO]: Loading 11 mods:
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.1
	- sodium 0.6.0-snapshot+mc1.21.1-local
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   \-- fabric-resource-loader-v0 1.3.0+5659912919
```

![Screenshot 2024-09-25 at 14 30 56](https://github.com/user-attachments/assets/533aedc7-aa18-4e61-af69-64428cdc8289)

When using 1.21 with Sodium 0.5.11 there is no problem at all. The dots only appear in 0.6.0 builds for me.

**Comment by wirl** [comment]
@pajicadvance would it be preferred if I make a new issue about this? It seemed so related but maybe it's something different/new.

**Comment by wirl** [comment]
Lmao, it's not fixed but if you ignore people who're trying to contribute, then sure, call it fixed. What a joke.

**Comment by wirl** [comment]
I'll just delete my comments and move to VulkanMod which is way more performant anyways.

**Comment by pajicadvance** [comment]
There wasn't a response because we're still not sure if what's shown in your screenshot is the same issue as this one or not. Feel free to use whatever software you want, but don't be toxic on the issue tracker.
