### ISSUE TITLE
Custom particles from Polytone are not animated

### ISSUE THREAD

**Issue by MehVahdJukaar** [jellysquid3/Sodium#2740]
### Bug Description

Due to some reports that was sent to me, I noticed that people animated particle textures were not animating when sodium was on. 
Animation is a normal texture atlas .mcmeta driven texture loop animation.

Now these particles were added via Polytone but the mod itself just registers them to the vanilla registries and sets them up just like ones registered on mod boot, most importantly it doesnt touch stuff related to how the actual particle texture atlas is handled.

I did not look into this further.

### Reproduction Steps

Add a particle with Polytone and give it an animated texture. Texture will not be animated on the particle atlas.

### Log File

[2024-09-09-1.log](https://github.com/user-attachments/files/16931960/2024-09-09-1.log)

### Crash Report

[2024-09-09-1.log](https://github.com/user-attachments/files/16931960/2024-09-09-1.log)

**Comment by douira** [comment]
Potentially related to https://github.com/CaffeineMC/sodium-fabric/issues/2722?

**Comment by jellysquid3** [comment]
We're still in the process of determining the root cause of the problem. Some progress was made the other day, in which we identified some mods had broken resource reload listeners, that were causing problems with sprite finding in Sodium.

**Comment by jellysquid3** [comment]
[This change](https://github.com/CaffeineMC/sodium-fabric/commit/95259344b077f6aecf9141b627ce4f58b3dd6691) might resolve the issue. Can you see if the [nightly build](https://nightly.link/CaffeineMC/sodium-fabric/workflows/build-commit/dev/sodium-artifacts-dev.zip) works?

**Comment by MehVahdJukaar** [comment]
i'll try

**Comment by MehVahdJukaar** [comment]
Issue seems to persist with that too

**Comment by jellysquid3** [comment]
I do not understand what the issue would be here, and cannot reproduce it. Your mod does not do anything strange and it successfully hits the code path which marks the texture for being animated.

**Comment by MehVahdJukaar** [comment]
Yeah that's the thing me neither. It's just some textures on the particle atlas like all the others. I'll try the new nightly build if there's one

**Comment by Lolothepro** [comment]
Can you give a resource pack to reproduce the bug?

**Comment by PigCart** [comment]
ran into what seems to be the same issue with one of my own mods cosy critters.

disabling "animate only visible textures" restores the animations.

how i fixed on my end, mojmap:

1) not overriding the particle's render method.
i might be able to make a custom FacingCameraMode to handle rotations instead of overriding. idk ill have to try later. sometimes i want to also translate or render multiple quads though so if theres some way to do that without blocking mixins lemme know

2) using particle.setSprite() instead of setting the sprite directly (particle.sprite = blahblah)

**Comment by douira** [comment]
Is this issue resolved in 0.6 or 0.7? I recall we fixed some texture animation tracking bugs recently.

**Comment by Redls07** [comment]
Not fixed. I used Cosy Critters version [0.0.1a](https://modrinth.com/mod/cosy-critters/version/0.0.1a) for the test.

**Comment by MehVahdJukaar** [comment]
im still getting reports about this btw

**Comment by douira** [comment]
Can you provide a reproduction case for this? "Add a particle with Polytone and give it an animated texture. Texture will not be animated on the particle atlas." is not easily actionable.

**Comment by Lolothepro** [comment]
I don't see how the bug can be fixed if there is no resource pack available to reproduce it...

**Comment by Redls07** [comment]
As for my test, as PigCart said, this issue can be reproduced using the Cozy Critters [v0.0.1a](https://modrinth.com/mod/cosy-critters/version/0.0.1a) mod.
His mod adds animated birds to the world as particles, but with the "Animate only visible textures" option enabled, these birds will not be animated.
In version 0.0.2, he circumvented this problem in his mod using the methods he wrote about above.

https://github.com/user-attachments/assets/803b34a2-2953-47b2-877a-730488945375

**Comment by Lolothepro** [comment]
So the bug is only in 1.21.1?

**Comment by douira** [comment]
If it only happens on 1.21.1, do we have confirmation that this remains a bug on 0.8.13 for 1.21.1?

**Comment by Redls07** [comment]
> So the bug is only in 1.21.1?

I'm not sure, it's just that Cozy Critters v0.0.1a is only available on Fabric 1.21.1. I can't test this on other versions. It seems to me that other versions also have this problem, but it would be easier if we had a resource pack for tests

> do we have confirmation that this remains a bug on 0.8.13 for 1.21.1?

I tested it on version `0.8.13-beta.2` and the problem persists

**Comment by MehVahdJukaar** [comment]
> Can you provide a reproduction case for this? "Add a particle with Polytone and give it an animated texture. Texture will not be animated on the particle atlas." is not easily actionable.

I was told that it happens with VFX plus when looking at one of their animated particles like lantern moths I assume. However I'm also told there might have been other mods in the mix and results were inconsistent.

**Comment by douira** [comment]
Are the reports you said you are still getting for this consistent with each other? Can you provide reproduction cases of this bug sourced from those reports if they are indeed instances of this bug?

**Comment by Redls07** [comment]
> it happens with VFX plus when looking at one of their animated particles like lantern moths

I may be wrong, but there are no moths near the lanterns in [Visual Effects+](https://modrinth.com/resourcepack/visual-effects-plus).

**Comment by MehVahdJukaar** [comment]
Apologies I was thinking of recrafted pack..I'm trying to get the people that had this issue here so they can give more accurate report
