### ISSUE TITLE
Snow Real Magic snowlogged blocks are invisible when Sodium is present

### ISSUE THREAD

**Issue by zjjohn121110** [jellysquid3/Sodium#2848]
### Bug Description

Any block with snow on it (stairs, slabs, plants, etc) are invisible when Sodium is installed with SRM on Neoforge 1.21.1.

The mod will say it requires Indium to use Sodium, but as of 0.6 Indium is no longer needed to it may have to do with Sodium's FRAPI.

### Reproduction Steps

Put SRM and Sodium in an instance.
Open the game.
Load a world.
Place a block that cannot usually have snow layers on it (such as stairs)
Place the snow layer on the block and see it turn invisible

### Log File

[latest.log](https://github.com/user-attachments/files/17548891/latest.log)

### Crash Report

no crashlog

**Comment by jellysquid3** [comment]
The error message which the mod is giving about Indium being absent does not appear to be related to the problem.

**Comment by douira** [comment]
The warning message comes from this piece of code in SRM that is there from when indium was still required. https://github.com/Snownee/SnowRealMagic/blob/d1356fbe4f24b91c5b044e9819616fb44b7bbd6f/src/main/java/snownee/snow/util/ClientProxy.java#L66

**Comment by Lolothepro** [comment]
is this fixed in https://github.com/Snownee/SnowRealMagic/commit/119303083fcd2513afd7257d506dbd228afd4260 ?

**Comment by DarthCaesium** [comment]
Is it fixed now?

**Comment by douira** [comment]
A screenshot of the snow-logged blocks missing can be seen in this duplicate issue: https://github.com/CaffeineMC/sodium/issues/2925

**Comment by Soforak** [comment]
Same issue here
Here's some other screenshots if it helps

Without Sodium
![Image](https://github.com/user-attachments/assets/fab77c8e-1b92-4c96-a34d-7fa6fe1bd977)


With Sodium
![Image](https://github.com/user-attachments/assets/04cf3e4a-4f21-4f1f-aec3-2a16a81568bd)

**Comment by kontrola111** [comment]
> Same issue here Here's some other screenshots if it helps
> 
> Without Sodium ![Image](https://github.com/user-attachments/assets/fab77c8e-1b92-4c96-a34d-7fa6fe1bd977)
> 
> With Sodium ![Image](https://github.com/user-attachments/assets/04cf3e4a-4f21-4f1f-aec3-2a16a81568bd)

Hi, if you want play with shaders and Snow Real Magic, you should try embeddium + monocle + iris :)

**Comment by JumboGeronimo** [comment]
I'm using the latest version for Minecraft v 1.21.1 on Neoforge and am having the same issue

**Comment by ghost** [comment]
I also encountered this problem

**Comment by DylanJMas** [comment]
same probelm

**Comment by Oxlyntia** [comment]
i too have this issue and while yes switching to embedium works, then embedium breaks little tiles and the little tiles people say to use sodium wich breaks snow real magic and thus stuck with no shaders haha heres to hoping this can be fixed soon snowee has said its a sodium issue itself and not a snow real magic issue! :D

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/c062f1108895bf55aa4b8f89ff7b8a9817e95938. This was an oversight on our part.

**Comment by mpustovoi** [comment]
I'm still having this issue on NeoForge 1.21.1-21.1.141

Sodium mc1.21.1-0.6.9-neoforge
Snow! Real Magic! 12.0.2+neoforge
Kiwi 15.5.0+neoforge

Has the fix been released yet?

**Comment by Lucky-56** [comment]
no

look at the [milestone](https://github.com/CaffeineMC/sodium/milestone/16) for more info
