### ISSUE TITLE
"More Red” cables are not rendered correctly

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2906]
### Bug Description

"More Red” cables are not rendered correctly

![2024-12-03_20 08 23](https://github.com/user-attachments/assets/b467eaaf-8484-4aa2-9a57-3f069e248ad9)

### Reproduction Steps

Install More Red and place cables next to it

### Log File

https://mclo.gs/jF1pLOi

### Crash Report

*

**Comment by jellysquid3** [comment]
Not sure what the bug was here. But this is fixed in More Red 7.0.

**Comment by Abbie5** [comment]
could this issue be reopened please? more red 7.0 was only released for 1.21.3, so the issue still exists on 1.21.1, which is supported by sodium. [it's unknown whether the issue is on sodium's or more red's side](https://discord.com/channels/602796788608401408/752637878462578778/1337419790138085427), so there's a possibility there is a sodium bug on 1.21.1 that causes this issue and could be fixed
