### ISSUE TITLE
Fog occlusion hides chunks incorrectly with blindness effect

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Sodium#35]
### Expected Behavior
Chunks within vision should not be culled

### Actual Behavior
Having fog occlusion enabled will cause chunks to disappear when the player is very close, but not inside them, while the blindness effect is on the player.

### Reproduction Steps
Apply blindness effect, be near a chunk border, have fog occlusion enabled.

### Attachments
https://cdn.discordapp.com/attachments/651120262129123330/726131134970462228/2020-06-27_03-05-46-1.mp4

### System Information
- Java Version: AdoptOpenJDK 14
- CPU: i7 3770
- GPU: GTX 970

**Comment by jellysquid3** [comment]
Fixed with https://github.com/jellysquid3/sodium-fabric/commit/5568b4c2a9814243ec9efbda092e5448e484b50e.

**Comment by TwistedZero** [comment]
I am still encountering this issue:
https://streamable.com/95ly1k
Using the latest commit as of writing this: `d35cb02`

### System Information

- Java Version: 1.8.0_222 64-bit (OpenJDK Hotspot)
- CPU: Ryzen 5 2500u
- GPU: Vega 8 Integrated Graphics

**Comment by altrisi** [comment]
Still happening in 0.1.0, this should be reopened. It works a little bit better than in the original report, but it's definitely still a bug.

[Video](https://streamable.com/rs3n8w)
### System info:
- Java 1.8.0_51 x64
- CPU: Intel Core i7-7700
- GPU: nVidia GTX 1050

**Comment by LOuroboros** [comment]
I'm also encountering this bug. I was about to open an issue for it, but thankfully, I was smart enough to check for a change, hahaha.

https://streamable.com/kfjram

### System Info:
- Java 1.8.0_51 x64
- CPU: Intel Core i3 2120
- GPU: Gigabyte's NVIDIA GeForce GT 1030, Driver Version 446.14

**Comment by Oberfail** [comment]
I'm also encountering this bug.

System Info:

    Java 1.8.0_51 x64
    CPU: R5 3600
    GPU: gtx1070, Driver Version 440.97

**Comment by CalXee** [comment]
The world becomes transparent when you fly high up. Here is a comparison between it on and off.
![2020-12-27_19 20 18](https://user-images.githubusercontent.com/68349758/103182486-98fea500-4879-11eb-8af6-f41d625381cb.png)
![2020-12-27_19 20 26](https://user-images.githubusercontent.com/68349758/103182487-99973b80-4879-11eb-85a1-d9f093edf44d.png)

**Comment by HedHogie** [comment]
I'm also experiencing this issue btw, it reduces lag so much but it's issue just won't let me.
