### ISSUE TITLE
Waterlogged stairs cause z-fighting

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Sodium#394]
### Expected Behavior
Water should not be visible through the back of the stair.

### Actual Behavior
The water and the stair z-fight. This happens regardless of the Compact Vertex Format, or Chunk Renderer, or any other setting in the advanced tab (and does not happen without sodium).

### Reproduction Steps
Waterlog some stairs, move >30 blocks away from them, facing their back (for me, Jokbon's screenshot doesn't look quite as far).

### Attachments
![2020-11-16_12 00 38](https://user-images.githubusercontent.com/64509677/99203720-5de16e80-2803-11eb-8598-339e865e7345.png)

![jokbon](https://media.discordapp.net/attachments/602805020861267968/777695754885529620/2020-11-16_02.44.39.png?width=1667&height=937)

### System Information
- Java Version: AdoptOpenJDK Java 15 64-bit
- CPU: i7 3770
- GPU: GTX 1070
- OS: Windows 10
Using Sodium 0.1.1-SNAPSHOT in my case, Jokbon seems to be on the stable release.

**Comment by CalXee** [comment]
Isn't this a vanilla bug? Are more sides of stairs Z fighting, or are they Z fighting more severely?

**Comment by LucilleTea** [comment]
I could not reproduce it in the same situation without sodium running, like I said. It may have happened in previous versions or in different circumstances.
Edit: Just confirmed with true vanilla 1.16.4, i don't see the issue there either. So that rules out Indigo fixing it.

**Comment by CodingRays** [comment]
While dealing with a similar bug in iris (https://github.com/IrisShaders/Iris/issues/242) i found the code that causes this. 
In sodiums `FluidRenderer.render` function while testing if sides are exposed the `isFluidExposed` function only tests if the next block contains the same fluid as the current block. Vanillia minecraft has an additional test for self occlusion which is implemented in `FluidRenderer.method_290710`.

**Comment by MeeniMc** [comment]
Issue is resolved in 0.4.10 (presumably since pr above merged)

**Comment by programaus** [comment]
> Issue is resolved in 0.4.10 (presumably since pr above merged)

This actually still persists

![Image](https://github.com/user-attachments/assets/1e649801-5754-4cc6-92e6-3e2f1d4e1fbf)
1.20.1 fabric, 0.5.11, indium 1.0.34

**Comment by douira** [comment]
Is this not the same as https://github.com/CaffeineMC/sodium/issues/2606 (a newer very similar issue), which was fixed in 0.6 with https://github.com/CaffeineMC/sodium/pull/2649 and https://github.com/CaffeineMC/sodium/pull/2907 ?

**Comment by programaus** [comment]
oh so 1.20.1 isnt supported my bad
